### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by jefferyong123** [weissi1994/LethalMod-ESP#2]
How do u install it?
i used thunderstore to install but it dont seem to work

**Comment by weissi1994** [comment]
i installed it manually first BepInEx following their "Installation (manual)" instructions (https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/).
ran the game once to generate configs etc.
and put the plugin in side the `BepInEx/plugins/` folder.
and started the game.

In the cmd windows started besides the actual game (might need to alt+tab if game is fullscreen) you should see a line like, can you verify the plugin gets loaded correctly?
```
[LethalMod] Plugin LethalMod is loaded!
```

**Comment by jefferyong123** [comment]
it did say it was loaded
other mods works it's just this mod with thunderstore
i will try manual and get back to you

**Comment by jefferyong123** [comment]
it seems to work now on v0.10
was on v0.8 back then
top left had the things saying if it is on or not
