### ISSUE TITLE
Its a bit laggy when i look to my right. Is there anything i can do about it?

### ISSUE THREAD

**Issue by TunaFish111** [weissi1994/LethalMod-ESP#4]
It lags when i look to my right. Is there any way i could fix that? I doubt its my pc

**Comment by weissi1994** [comment]
no its not your pc, its becaus paths were (re-)calculated on every frame.
this should have improved in `v0.0.10`, please get the latest version from

https://thunderstore.io/c/lethal-company/p/blob/LethalMod/

and report back if you still see lags

**Comment by TunaFish111** [comment]
Theres still a bit of lag it has improved. Is there any way i could just turn off the path entirely?
Edit: Its all fixed! thank you so much!
